### ISSUE TITLE
Swap licence for GPLv3 with Minecraft linking exception

### ISSUE THREAD

**Issue by Secret-chest** [tr7zw/EntityCulling#101]
So the only closed-source software this can be used in is Minecraft.

**Comment by tr7zw** [comment]
> So the only closed-source software this can be used in is Minecraft.

Doesn't solve that it would allow redistribution. Hence, the current license https://github.com/tr7zw/EntityCulling/blob/1.19.3/LICENSE-EntityCulling

**Comment by Secret-chest** [comment]
> > So the only closed-source software this can be used in is Minecraft.
> 
> Doesn't solve that it would allow redistribution. Hence, the current license https://github.com/tr7zw/EntityCulling/blob/1.19.3/LICENSE-EntityCulling

I don't understand. This would make it so clients can't use it.

**Comment by tr7zw** [comment]
Assuming you mean "clients" in the modpack client kind of sense(Feather/Essential/Labymod/BadLion/Lunar/etc): Clients can use it, if they:
a) download it from an official source(Modrinth/CurseForge)
b) are a non commercial client

So any normal modpack/client that just downloads from Modrinth and doesn't sell stuff like cosmetics(like Lunar does) is fine. The entire thing is to prevent people like Lunar from just taking my mods and baking them into their client to sell as a new feature, and to prevent reposting sites like 9minecraft(assuming they'd read and care about licenses). If you have some scenario that breaks one of the two conditions(like FTB rehosting the file, or a client with paid cosmetics wanting to integrate the mod), then get in contact.

If you instead mean "clients" like your normal Forge/Fabric install and putting the mod in there, that is explicitly allowed by the license(even tho it's technically not required, since Modrinths/Curses TOS also apply, so even ARR would be fine):
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software [...] to use, modify and compile the Software

**Comment by Secret-chest** [comment]
Could they? GPLv3 forbids using the licensed software in closed-source software. The Minecraft linking exception makes it useable with Minecraft, even though it is closed. I am no lawyer by any means.

**Comment by tr7zw** [comment]
But it's not GPLv3?

**Comment by tr7zw** [comment]
I have no intentions to put it under any GPL license. Also there is no need for the Minecraft exception, the lesser GPL already handles that(like I have here https://github.com/tr7zw/ItemSwapper/blob/1.19.3/LICENSE )

**Comment by Secret-chest** [comment]
> the lesser GPL already handles that(like I have here https://github.com/tr7zw/ItemSwapper/blob/1.19.3/LICENSE )

The lesser GPL allows adding it in clients (Badlion, Lunar etc.) The GPL with MC linking exception does not allow inclusion in clients because they're not also using that same licence.

**Comment by tr7zw** [comment]
I'm kinda lost what the topic here is^^. This mod is not under GPL/LGPL/GPL with MC linking exception, so what exactly is the point?

**Comment by Secret-chest** [comment]
I said I would appreciate if you would change the licence to that. But it's your mod, your choice. We can end this.

**Comment by tr7zw** [comment]
Since any GPL license still allows redistribution, not interested in changing my core mods to that.

**Comment by Secret-chest** [comment]
Okay, just asked because I'd like to use it in my modpack, and it may be on other sites too.

**Comment by tr7zw** [comment]
Like I said above, as long as it downloads from Modrinth or Curseforge, and you are not making money by selling stuff in that modpack, sure. Adding the mod to modpacks is covered by Modrinths/CurseForges TOS.
And if you have anything else in mind, get in contact.
