### ISSUE TITLE
Optimize EntityRenderDispatcher::shouldRender

### ISSUE THREAD

**Issue by FazziCLAY** [tr7zw/EntityCulling#107]
Hello :hand: 
Maybe it's worth moving the code canceling rendering from renderEntity to shouldRender?
And indeed there is a lot of unnecessary stuff in vanilla shouldRender using your mod.

Red - current
Green - my request

![image](https://user-images.githubusercontent.com/68351787/232744330-4d7e154b-6981-49d4-aad3-0a46ce17af9c.png)

**Comment by tr7zw** [comment]
If I remember correctly, skipping on shouldRender caused some unintended side effects, since that check assumes that the entity is outside of the frustum. Looking at it, it mainly just does the outline(glowing) preparations right after, which is the only "lot of unnecessary stuff". But then glowing entities can't be seen through walls. So I'd also need to check for glowing in my code... at which point this just gets done twice. So moving it into shouldRender wouldn't be any benefit.

**Comment by tr7zw** [comment]
Ah, also I need some stuff like the pose stack to for example render the nametag of culled entities. Cancelling at shouldRender would also remove the nametag, and I'd be missing the posestack to render it myself(since shouldRender only has the entity and frustum).
