### ISSUE TITLE
Culling Display

### ISSUE THREAD

**Issue by illystray** [tr7zw/EntityCulling#161]
Hello! I have a question. I saw in Github threads that сulling should work with Display models. But after trying it, I didn't see the result. Could you please help me?

I am using a model consisting of 2.6K objects.

I get 900 fps if the model is in an unloaded chunk
130 fps if I'm looking at the ball, the ball is hidden behind a wall of Block Display, the ball is hidden behind a wall of real blocks, I turned away from the ball. The mod doesn't seem to affect the result. I was expecting the fps to increase if the orb disappeared from line of sight. Maybe I'm doing something wrong? I apologize. Can you please give me a hint

![image](https://github.com/tr7zw/EntityCulling/assets/125918226/ced85ee9-098e-4459-a2cf-7c8c75f6bee4)

**Comment by tr7zw** [comment]
You need to set a culling box to the entities. Vanilla default behavior is 0, disabling culling for them in general(also frustum culling of vanilla/sodium, what you are experiencing that not looking at them at all still tanks the fps). Also of note, they wont behave blockingly, so that giant acacia wall made out of one display entity won't do anything.
