### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by matthewelmer** [tr7zw/EntityCulling#173]
How do I install this mod?

It might be helpful to have a short mention of the process in the README, even if it's just a link to some wiki.

**Comment by tr7zw** [comment]
There is no process in the readme because explaining on how to install Fabric/NeoForge/Forge or a launcher like CurseForge/Modrinth/Prism/MultiMC is not really the job of the mods? If you in general don't know how to mod Minecraft, check out a video on youtube or for example the fabricmc website.
If you have Fabric/NeoForge or Forge already setup, then just download the correct file from Modrinth or CurseForge and put it into the mods folder.
