### ISSUE TITLE
Mod Menu integration.

### ISSUE THREAD

**Issue by Xrey274** [tr7zw/EntityCulling#19]
I'd be a massively more convenient if I could edit the config from within the Mod Menu.

**Comment by tr7zw** [comment]
Well, currently the config only contains stuff that currently can't change on the fly(and that people shouldn't really change). So adding a config screen to ModMenu would require adding an external dependency to the config screen api or package it into the jar(doubling the mod size). So for now I'll pass on this since 99% of people don't need the config at all and doubling the jar size/adding dependencies would be more annoying than anything.
