### ISSUE TITLE
When looking at a painting in a certain angle while right next to it, it disappears

### ISSUE THREAD

**Issue by he3als** [tr7zw/EntityCulling#24]
When looking at a painting in a certain angle while right next to it, it disappears.

**Comment by tr7zw** [comment]
This is a vanilla bug and happens with Armorstands/Players/many other bigger entities too. To test rather something is caused by the culling mod you can bind a toggle in the controlls. If it shows up/vanishes when pressing this toggle, then it's a bug of the mod.

Edit: after testing around for a bit I did manage to replicate it, I assumed you meant camera angle and not angle to the painting. I'll look into it.

**Comment by he3als** [comment]
Also occasionally happens with item frames.

**Comment by tr7zw** [comment]
Fixed in the newest release, this took way too long to debug :/
