### ISSUE TITLE
Sodium's option

### ISSUE THREAD

**Issue by Madis0** [tr7zw/EntityCulling#40]
How does this mod interact with Sodium's Entity Culling option? Is there any harm or benefit in keeping both enabled, or perhaps the mod already implicitly disables Sodium's option?

**Comment by tr7zw** [comment]
From the modpage:

Compatibility

This has been tested with other mods, Optifine(Optifabric), Canvas, and Sodium, in all cases resulting in massive fps gains in places like Game Server lobbies.

You might wonder why it does increase the FPS with Sodium(and Canvas) since Sodium has "Use Entity Culling" in its Advanced settings and enabled by default. The difference is that Sodium does a really quick pass based on the visible chunks, being way less aggressive and thereby still rendering entities that just happen to be in visible chunks, but not visible themselves.

**Comment by Madis0** [comment]
Yes, I read that but it doesn't answer the question.

* It is compatible with Sodium the mod but how does it interact with the setting?
* It is better than Sodium's setting but does it mean Sodium's has to be disabled, or do they "get along" somehow automatically?

**Comment by tr7zw** [comment]
> It is compatible with Sodium the mod but how does it interact with the setting?
This has been tested with [...] Sodium.

>It is better than Sodium's setting but does it mean Sodium's has to be disabled, or do they "get along" somehow automatically?
They are 2 different features that do different things and work at the same time. So you can have both active.

**Comment by Madis0** [comment]
Got it, thanks!
