### ISSUE TITLE
Block entities from Enhanced Block Entities mod do not get culled

### ISSUE THREAD

**Issue by BobdaBiscuit** [tr7zw/EntityCulling#41]
Hey, I've got a small issue report for a soft-incompatibility.

Testing Entity Culling 1.3.3 with Enhanced Block Entities 0.5+1.17 has blocks such as chests not get culled when occluded, or when outside the 64 block render distance. Remaining visible the entire time.

Disabling chest optimizations on EBE causes Entity Culling to correctly remove chests again.

Thanks for your time.

**Comment by tr7zw** [comment]
Thats because of what the Enhanced Block Entities mod does. It replaces the Block-Entity Renderer of chests with a static one. Therefore it's not a rendered Block-Entity any more and won't get culled(since there is no reason for that, because it behaves like for example a fencepost). So keep the chest optimizations active, since it will increase the normal performance, and reduce the amount of things that this mod needs to calculate, giving a net gain over just entity culling.

**Comment by BobdaBiscuit** [comment]
Righto, thanks for the explanation!
