### ISSUE TITLE
Requiem permanent redness after taking damage as mob

### ISSUE THREAD

**Issue by AeiouEnigma** [tr7zw/EntityCulling#48]
When using Entity Culling and Requiem, player-possessed mobs become permanently red-colored after taking damage, instead of only being red for the moment when they receive damage.
![2021-12-09_11 02 33](https://user-images.githubusercontent.com/3160746/145432052-2774c8ff-d686-42d7-a911-763419aaad50.png)

**Comment by tr7zw** [comment]
I have to test this, but somewhat sure this should have nothing to do with EntityCulling? The only option would be that the Entity you possess gets stored in some odd location, causing it to get culled somehow.

**Comment by AeiouEnigma** [comment]
I agree it's a very odd issue, but I've tested with Requiem alone and with just Requiem and Entity Culling. Using only Requiem, the issue does not occur. It occurs when adding Entity Culling alongside Requiem.

I think I'll open an issue on Requiem's page as well, for good measure.

**Comment by tr7zw** [comment]
Nah leave it here first if it really happens because of EntityCulling.

**Comment by tr7zw** [comment]
Ok did a quick test, it is in fact the culling. It's somewhat certain that the tick culling is the reason for that, so I guess I'll look into either updating the hurt timer, or look into putting the requiem player mobs on the ignore list.

**Comment by tr7zw** [comment]
Ok this one is a bit problematic because the entities seem to be vanilla entities, so adding them to whitelist won't work. Also, I don't seem to find a method inside the Requiem API to check for this state. I did add a dynamic whitelist system that other mods can use to on the fly whitelist mobs, so that could be used from their end to fix this. A workaround is to go into the config and disable the tick culling.

**Comment by tr7zw** [comment]
Ok next time take my own advice and just implement the hurt timer... Fixed^^
