### ISSUE TITLE
Invisible frames and paintings

### ISSUE THREAD

**Issue by QueenUlyana** [tr7zw/EntityCulling#49]
Frames and paintings are visually invisible even when you are near them. Is there any way to fix this?
![2021-12-11_19 36 34](https://user-images.githubusercontent.com/83131824/145708470-698da13b-9d8a-4bcd-8c83-7577842278ef.png)
![2021-12-11_19 36 38](https://user-images.githubusercontent.com/83131824/145708474-cd956e10-2378-4a4b-80b3-773a48abb6f3.png)

**Comment by tr7zw** [comment]
> Is there any way to fix this?

It's a known issue that I just haven't yet had the time to nail down how to fix it correctly. I know somewhat why it happens and how to "fix" it, but it costs too much performance (on the culling thread, not fps related) to do that(disable the cache). 
This bug is tracked in #39 , for now the next step is to get a clean example to reproduce this (flatmap with the least amount of required entities to reproduce the bug), to then look step for step on why this happens.
