### ISSUE TITLE
Holograms in the form of images (Using a custom Resource pack) don't display correctly

### ISSUE THREAD

**Issue by Blobanium** [tr7zw/EntityCulling#5]
so i installed this mod and when i went on the mineclub server, all of the holograms that are images aren't displaying right and they all appear in black

What its supposed to display (i circled them to know what should be payed attention to.)
![Inked2021-02-23_12 24 24_LI](https://user-images.githubusercontent.com/45613796/108905505-a368c100-75d4-11eb-91b0-7319c3c46abd.jpg)

What its showing (they may appear invisible but its just showing in black)
![Inked2021-02-23_12 18 09_LI](https://user-images.githubusercontent.com/45613796/108905597-c1362600-75d4-11eb-8e88-6b5cf29baa59.jpg)

Im using mod version 1.0.1 also

Tell me if i need anything else thanks.

**Comment by tr7zw** [comment]
Hmm try the non-optimized nametag version. I guess for now I'll not provide builds that have this, since it is probably too jank for some player. Can you report other things like issues with custom models (since I didn't test on servers like this) or how it impacts the fps compared to not using the mod?

**Comment by Blobanium** [comment]
that did seem to fix the issue with the unoptimized nametag version, will check the FPS Differences with and without the mod (including the vanilla nametags also)

**Comment by tr7zw** [comment]
Yea like I said, I'll probably bin the nametag stuff for now since making the culling as seamless as possible has priority over that for now.

**Comment by Blobanium** [comment]
After Performing FPS Benchmarks with each variant it seemed that the Vanilla Tags Version got some improvement ~120FPS  and the optimized version got around 140-150FPS. Without the mod i see around 110 FPS

also there doesn't seem to be any issues with custom models.

**Comment by tr7zw** [comment]
Hm sounds good. They probably don't have much outside of the lobby, that's why the improvement is comparably smaller. Also kinda sad for the 20-30fps more in regards to the nametags, but I'll have to invest more time into them to get them to behave better. I'll publish a new release now that has some fixes in regards to beacons/spectator mode/less memory usage, showing how long the culling in the async thread takes, and I'll remove the nametag part for it.
