### ISSUE TITLE
Entities become invisible over max build height

### ISSUE THREAD

**Issue by Justsnoopy30** [tr7zw/EntityCulling#9]

**Comment by supersaiyansubtlety** [comment]
Can confirm, and it's based on the camera entity, not the player entity. 

https://user-images.githubusercontent.com/618276/111692292-89458b80-87ec-11eb-9c4d-c7131f2a1d22.mp4

You can see the height in the upper left. Just looking down in 3rd person causes entities to disappear because the camera entity moves above build limit. 
The boats, other players, and the client player all disappear.
